version: 0.0
os: linux
files:
  - source: /  # source from the root of the repo
    destination: /opt/fastapi
  - source: scripts/  # includes all scripts from your repo
    destination: /opt/fastapi/scripts/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh  # Just one occurrence
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
