version: 0.0
os: linux
files:
  - source: .
    destination: /opt/tgp-backend
permissions:
  - object: /opt/tgp-backend
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: scripts/restart_service.sh
      timeout: 30
      runas: ec2-user

