version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      # Add your test commands here (e.g., pytest)

  post_build:
    commands:
      - echo "Stopping existing application..."
      - pkill -f "uvicorn" || true
      - echo "Preparing for deployment..."
      - ls -lah

artifacts:
  files:
    - '**/*'  # Include all files
  base-directory: '.'  # Use current directory as base
  discard-paths: no
